services:
  - type: web
    name: shop-management
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn shop.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: shop.settings
      - key: PYTHON_VERSION
        value: 3.10
