# Generated by Django 5.2.2 on 2025-06-10 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "order_id",
                    models.AutoField(
                        db_column="order_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "payment_order_code",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        unique=True,
                        verbose_name="Mã đơn hàng PayOS",
                    ),
                ),
                (
                    "user",
                    models.CharField(
                        db_column="user", max_length=150, verbose_name="Tên người dùng"
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(
                        db_column="customer_name",
                        max_length=100,
                        verbose_name="Tên khách hàng",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        db_column="address", max_length=255, verbose_name="Địa chỉ"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_column="phone_number",
                        max_length=20,
                        verbose_name="Số điện thoại",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        db_column="total_price",
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Tổng tiền",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Đang chờ xử lý"),
                            ("PendPay", "Chờ thanh toán"),
                            ("Confirmed", "Đã xác nhận"),
                            ("Processing", "Đang xử lý"),
                            ("Shipped", "Đã gửi hàng"),
                            ("Delivered", "Đã giao hàng"),
                            ("Canceled", "Đã hủy"),
                            ("PayError", "Lỗi thanh toán"),
                            ("StockErr", "Hết hàng (cần hoàn tiền)"),
                            ("PayExp", "Thanh toán hết hạn"),
                            ("Failed", "Thất bại"),
                        ],
                        db_column="status",
                        default="Pending",
                        max_length=20,
                        verbose_name="Trạng thái",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Ngày tạo"
                    ),
                ),
                (
                    "payment_link",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Link thanh toán",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Mã giao dịch PayOS",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đơn hàng",
                "verbose_name_plural": "Các đơn hàng",
                "db_table": "orders",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "product_id",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Mã sản phẩm",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=25, verbose_name="Tên sản phẩm"),
                ),
                (
                    "product_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="product_images/",
                        verbose_name="Ảnh sản phẩm",
                    ),
                ),
                (
                    "company",
                    models.CharField(max_length=25, verbose_name="Nhà sản xuất"),
                ),
                (
                    "product_description",
                    models.TextField(verbose_name="Mô tả sản phẩm"),
                ),
                (
                    "quantity_in_stock",
                    models.PositiveIntegerField(verbose_name="Số lượng tồn kho"),
                ),
                (
                    "sell_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Giá bán"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sản phẩm",
                "verbose_name_plural": "Các sản phẩm",
            },
        ),
        migrations.CreateModel(
            name="OrderDetails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        db_column="quantity", verbose_name="Số lượng"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        db_column="order_id_fk",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.orders",
                        verbose_name="Đơn hàng",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id_fk",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.product",
                        verbose_name="Sản phẩm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chi tiết đơn hàng",
                "verbose_name_plural": "Các chi tiết đơn hàng",
                "db_table": "orderdetails",
                "unique_together": {("order", "product")},
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 - Rất tệ"),
                            (2, "2 - Tệ"),
                            (3, "3 - Bình thường"),
                            (4, "4 - Tốt"),
                            (5, "5 - Rất tốt"),
                        ],
                        verbose_name="Xếp hạng",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Bình luận"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Ngày cập nhật"),
                ),
                (
                    "order_detail",
                    models.OneToOneField(
                        help_text="Mục cụ thể trong đơn hàng đang được đánh giá.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="products.orderdetails",
                        verbose_name="Chi tiết đơn hàng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đánh giá sản phẩm",
                "verbose_name_plural": "Các đánh giá sản phẩm",
                "db_table": "product_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "ord",
                    models.AutoField(
                        db_column="ord", primary_key=True, serialize=False
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        db_column="quantity", verbose_name="Số lượng"
                    ),
                ),
                ("user", models.CharField(db_column="user", max_length=150)),
                (
                    "product",
                    models.ForeignKey(
                        db_column="product_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="Sản phẩm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Giỏ hàng",
                "verbose_name_plural": "Các giỏ hàng",
                "db_table": "cart",
                "unique_together": {("user", "product")},
            },
        ),
    ]
