# Generated by Django 2.2.9 on 2025-05-14 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(db_column='order_id', primary_key=True, serialize=False)),
                ('user', models.CharField(db_column='user', max_length=150)),
                ('customer_name', models.CharField(db_column='customer_name', max_length=100)),
                ('address', models.CharField(db_column='address', max_length=255)),
                ('phone_number', models.CharField(db_column='phone_number', max_length=20)),
                ('total_price', models.DecimalField(db_column='total_price', decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled')], db_column='status', default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=25)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('company', models.CharField(max_length=25)),
                ('product_description', models.TextField()),
                ('quantity_in_stock', models.PositiveIntegerField()),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(db_column='quantity')),
                ('order_id', models.ForeignKey(db_column='order_id_fk', on_delete=django.db.models.deletion.CASCADE, to='products.Orders')),
                ('product_id', models.ForeignKey(db_column='product_id_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product')),
            ],
            options={
                'db_table': 'orderdetails',
                'unique_together': {('order_id', 'product_id')},
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('ord', models.AutoField(db_column='ord', primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(db_column='quantity')),
                ('user', models.CharField(db_column='user', max_length=150)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'db_table': 'cart',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
